# """    Outline
#     
# """    
label script4:
    call hideMapview
    ""
    "Nice, I'm much earlier than i was before."
    "She's not here yet."
    "I might be able to repay her now for that last time i was late."
    "But... will it be okay if I ordered a drink before she came? Like she did for me?"
    "That time, she guessed correctly what flavor i like to buy from this place." 
    "I don't know if she would appreciate me doing that for her. I know the drink she got was... this one! Red Velvet?"

    "What would she think? Is that weird? Like I'm stalking her?"
    "When she did it for me i just accepted it as it was convenient and... huh? how did she know?"
    "That brain of hers might just be too smart for me. Yeah. She's a topnotcher after all."
    "Red Velvet.. i suppose I'll try that one out too."
    "Ahh! I do know that she liked the spinach dip pizza we got last time, maybe I could order that one again. Yeah!"

    "..."
    "So i ended up getting 2 red velvet frappes and 1 whole spinach dip pizza. For sharing!"

    "Yep... it's served already, but she's not here yet."
    "I try to resist eating the pizza for myself. I didn't open the box yet."
    "But i got to try the red velvet frappe. It's really good."
    "Aaand just like that, i drank all of it."
    "I took some time to myself.. Until..."
    "Someone entered the cafe! Is it her?"
    "That's some other girl... she's... approaching here?"
    "She looks like... Ellie? Lisa's roommate."
    show Ellie 
    e "So you're really here."
    j "..."
    e"You waiting for someone? I will sit here now."
    j "Ah! G-go ahead!"
    "She lands her elbows on the table, locks her fingers together, then rests her chin on them. Then she gives me a gaze like that of a detective skimming for any signs of criminal activity. At least that is what it feels like."
    "My upper body retreats back insinctively, in response to her leers."
    e "John."
    j "Uhh what can i do for you?"
    e "Lisa isn't coming today."
    e "You can forget about your little date here."
    j "Wa- did something happen? Is she okay?"
    e "You stay away from her that's what!"
    j "B-but the pizza! A-and this drink!"
    e "Guh!"
    j  "Where is she?"
    e "Why do you care!"
    e "I-I forbid you!"
    j "Forbid? But we were-"
    e "Why were you together? And that was... your house?!"
    j "Huh?! She's just! It's work! The internship!"
    j "Hilbert was with us! There was some trou-"
    e "You were....!!"
    j "I can explain!!"
    e "I don't trust men like you."
    e "I bet you're thinking something nasty right now!"
    j "What!!"
    "She got worked up.. just what is her problem with me?"
    j "uhhh... will you calm down? "
    extend "Please?"
    "I push the pizza box closer to her, and lift the cover open."
    j "You can... take some."
    e "Huh?! You idiot, you bought this for her, don't just give it to-..."
    e "What's your deal? Don't think you can sway me with.."
    j "The drink is still cold.."
    e "Damn it. listen!" 
    e "You didn't do anything with Lisa that's.. that's..."
    j "Like i said it's work!"
    e "In your house!!.... With... Hilbert??"
    j "What are you implying?!"
    j "We solved some problems together.. does that suffice? It was.. complicated!"
    e "You don't have the hots for Lisa?"
    j "I do!"
    e "HUUUUH?!"
    "Yikes. Did i say that out loud?"
    "In response to that, she slammed at the table and stood up violently."
    e "You dirty!"
    e"You can't even look me in the eyes straight!"
    "It's not my fault her breasts are distracting my view..."
    e "Give me some of this you idiot."

    return
